INFO - Log de condiciones convertidas a formato pandas
INFO - Inicio del proceso de validación de datos.
INFO - Se encontraron 478 condiciones.
ERROR - P02A01 = 2 y (P02A04A>0|P02A04B esta en (1,2,3,4,5,6,7,8,9,10,11,12,13,98): ('EOF in multi-line statement', (2, 0)). Error de nan
ERROR - PPA03  > 2 Y (P05A04 >=1 o P05A04<=10 o P05A04=98): Python keyword not valid identifier in numexpr query (<unknown>, line 1). Error de AS
ERROR - PPA03 <= 6 y(P05B05A = 2 y P05B05B no es vacío): Python keyword not valid identifier in numexpr query (<unknown>, line 1). Error de AS
ERROR - PPA03 >= 6 y P05C01 está en (1,2) o P05C02 está en (1,2,3,4,5,6,98) o P05C03 está en (1,2) o P05C04 está en (1,2,3,4,98) o P05C05 está en (1,2,3,4,5,6,7,8,9,98) o P05C06 está en (1,2,3,4,5,6,7,8,9,10,11,12,98) o P05C07A no es vacío o P05C07B no es vacío o P05C08A está en (1,2,3,4,5,6,7,8,9,10,11,12,98) o P05C08B está en (1,2,3,4,5,6,7,8,9,10,11,12,98) o P05C09A no es vacío o P05C09B no es vacío o P05C09C no es vacío o P05C09D no es vacío o P05C09E no es vacío o P05C09F no es vacío o P05C09G no es vacío o P05C010 está en (1,2): 'NoneType' object is not subscriptable. Error de VO
ERROR - P05D07 <= 9| P05D07 = 98) & P05D08A es (vacio) & P05D08B es (vacio): ('EOF in multi-line statement', (2, 0)). Error de LA
ERROR -  P05D12A = 1 & P05D12B es (vacio)) : ('EOF in multi-line statement', (2, 0)). Error de LA
ERROR - (P06A09A esta en (1,2,3) & (P06A09B <= 0): ('EOF in multi-line statement', (2, 0)). Error de MC
ERROR - P10A03=1 y P10A04 está en (1,2): Python keyword not valid identifier in numexpr query (<unknown>, line 1). Error de PH
ERROR - P10A04=1 y P10A05 está en (1,2): Python keyword not valid identifier in numexpr query (<unknown>, line 1). Error de PH
ERROR - P10A06 = 2 y (P10A07 está en (1,2,3,4,5,6,7,8,9,10,11,12,13,14,98) : ('EOF in multi-line statement', (2, 0)). Error de MP
ERROR - P10A05=1 y P10A06 está en (1,2): Python keyword not valid identifier in numexpr query (<unknown>, line 1). Error de PH
ERROR - PPA03 >= 7 Y (P10B01=1 y P10B03 no está en (1,2,3,4,5,6,7,8,9,10,11,12,13)): Python keyword not valid identifier in numexpr query (<unknown>, line 1). Error de MP
ERROR - PPA03 >= 7 Y (P10B01=2 & (P10B04>0)): Python keyword not valid identifier in numexpr query (<unknown>, line 1). Error de MP
ERROR - PC10C21<5 y P10C22 no es vacio: 'NoneType' object is not subscriptable. Error de PH
ERROR - P10C21 < 4 P10C41 no esta en (1, 2): Python keyword not valid identifier in numexpr query (<unknown>, line 1). Error de PH
ERROR - (P10C21 esta en (5,6,7,8)) y P10C51A no está en (1): only list-like objects are allowed to be passed to isin(), you passed a [int]. Error de PH
ERROR - PPD06 es (vacio): "['DEPTO', 'MUPIO', 'SECTOR', 'ESTRUCTURA', 'VIVIENDA', 'HOGAR', 'ENCUESTADOR'] not in index". Error de LG
ERROR - PPD06 = 0: "['DEPTO', 'MUPIO', 'SECTOR', 'ESTRUCTURA', 'VIVIENDA', 'HOGAR', 'ENCUESTADOR'] not in index". Error de LG
ERROR - (PPD06 > 25 y PPD06 < 98) o PPD06 > 98: "['DEPTO', 'MUPIO', 'SECTOR', 'ESTRUCTURA', 'VIVIENDA', 'HOGAR', 'ENCUESTADOR'] not in index". Error de LG
ERROR - PPD07 es (vacio): "['DEPTO', 'MUPIO', 'SECTOR', 'ESTRUCTURA', 'VIVIENDA', 'HOGAR', 'ENCUESTADOR'] not in index". Error de LG
ERROR - PPD07 = 0: "['DEPTO', 'MUPIO', 'SECTOR', 'ESTRUCTURA', 'VIVIENDA', 'HOGAR', 'ENCUESTADOR'] not in index". Error de LG
ERROR - (PPD07 > 25 y PPD07 < 98) o PPD07 > 98: "['DEPTO', 'MUPIO', 'SECTOR', 'ESTRUCTURA', 'VIVIENDA', 'HOGAR', 'ENCUESTADOR'] not in index". Error de LG
ERROR - PPD08 es (vacio): "['DEPTO', 'MUPIO', 'SECTOR', 'ESTRUCTURA', 'VIVIENDA', 'HOGAR', 'ENCUESTADOR'] not in index". Error de LG
ERROR - PPD08 = 0: "['DEPTO', 'MUPIO', 'SECTOR', 'ESTRUCTURA', 'VIVIENDA', 'HOGAR', 'ENCUESTADOR'] not in index". Error de LG
ERROR - PPD08 > 2: "['DEPTO', 'MUPIO', 'SECTOR', 'ESTRUCTURA', 'VIVIENDA', 'HOGAR', 'ENCUESTADOR'] not in index". Error de LG
WARNING - R[write to console]: Loading required package: DBI

WARNING - R[write to console]: Total de inconsistencias: 139

WARNING - R[write to console]: >> InconsistenciasGRUPO11.xlsx -> 7

WARNING - R[write to console]: >> InconsistenciasGRUPO9.xlsx -> 12

WARNING - R[write to console]: >> InconsistenciasGRUPO22.xlsx -> 4

WARNING - R[write to console]: >> InconsistenciasGRUPO26.xlsx -> 19

WARNING - R[write to console]: >> InconsistenciasGRUPO1.xlsx -> 1

WARNING - R[write to console]: >> InconsistenciasGRUPO23.xlsx -> 7

WARNING - R[write to console]: >> InconsistenciasGRUPO13.xlsx -> 11

WARNING - R[write to console]: >> InconsistenciasGRUPO5.xlsx -> 21

WARNING - R[write to console]: >> InconsistenciasGRUPO29.xlsx -> 6

WARNING - R[write to console]: >> InconsistenciasGRUPO16.xlsx -> 3

WARNING - R[write to console]: >> InconsistenciasGRUPO38.xlsx -> 14

WARNING - R[write to console]: >> InconsistenciasGRUPO28.xlsx -> 5

WARNING - R[write to console]: >> InconsistenciasGRUPO34.xlsx -> 2

WARNING - R[write to console]: >> InconsistenciasGRUPO17.xlsx -> 7

WARNING - R[write to console]: >> InconsistenciasGRUPO12.xlsx -> 2

WARNING - R[write to console]: >> InconsistenciasGRUPO21.xlsx -> 2

WARNING - R[write to console]: >> InconsistenciasGRUPO6.xlsx -> 4

WARNING - R[write to console]: >> InconsistenciasGRUPO3.xlsx -> 4

WARNING - R[write to console]: >> InconsistenciasGRUPO24.xlsx -> 5

WARNING - R[write to console]: >> InconsistenciasGRUPO20.xlsx -> 1

WARNING - R[write to console]: >> InconsistenciasGRUPO32.xlsx -> 1

WARNING - R[write to console]: >> InconsistenciasGRUPO27.xlsx -> 1

INFO - Log de condiciones convertidas a formato pandas
INFO - Inicio del proceso de validación de datos.
INFO - Se encontraron 478 condiciones.
ERROR - P02A01 = 2 y (P02A04A>0|P02A04B esta en (1,2,3,4,5,6,7,8,9,10,11,12,13,98): ('EOF in multi-line statement', (2, 0)). Error de nan
ERROR - PPA03  > 2 Y (P05A04 >=1 o P05A04<=10 o P05A04=98): Python keyword not valid identifier in numexpr query (<unknown>, line 1). Error de AS
ERROR - PPA03 <= 6 y(P05B05A = 2 y P05B05B no es vacío): Python keyword not valid identifier in numexpr query (<unknown>, line 1). Error de AS
ERROR - PPA03 >= 6 y P05C01 está en (1,2) o P05C02 está en (1,2,3,4,5,6,98) o P05C03 está en (1,2) o P05C04 está en (1,2,3,4,98) o P05C05 está en (1,2,3,4,5,6,7,8,9,98) o P05C06 está en (1,2,3,4,5,6,7,8,9,10,11,12,98) o P05C07A no es vacío o P05C07B no es vacío o P05C08A está en (1,2,3,4,5,6,7,8,9,10,11,12,98) o P05C08B está en (1,2,3,4,5,6,7,8,9,10,11,12,98) o P05C09A no es vacío o P05C09B no es vacío o P05C09C no es vacío o P05C09D no es vacío o P05C09E no es vacío o P05C09F no es vacío o P05C09G no es vacío o P05C010 está en (1,2): 'NoneType' object is not subscriptable. Error de VO
ERROR - P05D07 <= 9| P05D07 = 98) & P05D08A es (vacio) & P05D08B es (vacio): ('EOF in multi-line statement', (2, 0)). Error de LA
ERROR -  P05D12A = 1 & P05D12B es (vacio)) : ('EOF in multi-line statement', (2, 0)). Error de LA
ERROR - (P06A09A esta en (1,2,3) & (P06A09B <= 0): ('EOF in multi-line statement', (2, 0)). Error de MC
ERROR - P10A03=1 y P10A04 está en (1,2): Python keyword not valid identifier in numexpr query (<unknown>, line 1). Error de PH
ERROR - P10A04=1 y P10A05 está en (1,2): Python keyword not valid identifier in numexpr query (<unknown>, line 1). Error de PH
ERROR - P10A06 = 2 y (P10A07 está en (1,2,3,4,5,6,7,8,9,10,11,12,13,14,98) : ('EOF in multi-line statement', (2, 0)). Error de MP
ERROR - P10A05=1 y P10A06 está en (1,2): Python keyword not valid identifier in numexpr query (<unknown>, line 1). Error de PH
ERROR - PPA03 >= 7 Y (P10B01=1 y P10B03 no está en (1,2,3,4,5,6,7,8,9,10,11,12,13)): Python keyword not valid identifier in numexpr query (<unknown>, line 1). Error de MP
ERROR - PPA03 >= 7 Y (P10B01=2 & (P10B04>0)): Python keyword not valid identifier in numexpr query (<unknown>, line 1). Error de MP
ERROR - PC10C21<5 y P10C22 no es vacio: 'NoneType' object is not subscriptable. Error de PH
ERROR - P10C21 < 4 P10C41 no esta en (1, 2): Python keyword not valid identifier in numexpr query (<unknown>, line 1). Error de PH
ERROR - (P10C21 esta en (5,6,7,8)) y P10C51A no está en (1): only list-like objects are allowed to be passed to isin(), you passed a [int]. Error de PH
ERROR - PPD06 es (vacio): "['DEPTO', 'MUPIO', 'SECTOR', 'ESTRUCTURA', 'VIVIENDA', 'HOGAR', 'ENCUESTADOR'] not in index". Error de LG
ERROR - PPD06 = 0: "['DEPTO', 'MUPIO', 'SECTOR', 'ESTRUCTURA', 'VIVIENDA', 'HOGAR', 'ENCUESTADOR'] not in index". Error de LG
ERROR - (PPD06 > 25 y PPD06 < 98) o PPD06 > 98: "['DEPTO', 'MUPIO', 'SECTOR', 'ESTRUCTURA', 'VIVIENDA', 'HOGAR', 'ENCUESTADOR'] not in index". Error de LG
ERROR - PPD07 es (vacio): "['DEPTO', 'MUPIO', 'SECTOR', 'ESTRUCTURA', 'VIVIENDA', 'HOGAR', 'ENCUESTADOR'] not in index". Error de LG
ERROR - PPD07 = 0: "['DEPTO', 'MUPIO', 'SECTOR', 'ESTRUCTURA', 'VIVIENDA', 'HOGAR', 'ENCUESTADOR'] not in index". Error de LG
ERROR - (PPD07 > 25 y PPD07 < 98) o PPD07 > 98: "['DEPTO', 'MUPIO', 'SECTOR', 'ESTRUCTURA', 'VIVIENDA', 'HOGAR', 'ENCUESTADOR'] not in index". Error de LG
ERROR - PPD08 es (vacio): "['DEPTO', 'MUPIO', 'SECTOR', 'ESTRUCTURA', 'VIVIENDA', 'HOGAR', 'ENCUESTADOR'] not in index". Error de LG
ERROR - PPD08 = 0: "['DEPTO', 'MUPIO', 'SECTOR', 'ESTRUCTURA', 'VIVIENDA', 'HOGAR', 'ENCUESTADOR'] not in index". Error de LG
ERROR - PPD08 > 2: "['DEPTO', 'MUPIO', 'SECTOR', 'ESTRUCTURA', 'VIVIENDA', 'HOGAR', 'ENCUESTADOR'] not in index". Error de LG
WARNING - R[write to console]: Total de inconsistencias: 139

WARNING - R[write to console]: >> InconsistenciasGRUPO11.xlsx -> 7

WARNING - R[write to console]: >> InconsistenciasGRUPO9.xlsx -> 12

WARNING - R[write to console]: >> InconsistenciasGRUPO22.xlsx -> 4

WARNING - R[write to console]: >> InconsistenciasGRUPO26.xlsx -> 19

WARNING - R[write to console]: >> InconsistenciasGRUPO1.xlsx -> 1

WARNING - R[write to console]: >> InconsistenciasGRUPO23.xlsx -> 7

WARNING - R[write to console]: >> InconsistenciasGRUPO13.xlsx -> 11

WARNING - R[write to console]: >> InconsistenciasGRUPO5.xlsx -> 21

WARNING - R[write to console]: >> InconsistenciasGRUPO29.xlsx -> 6

WARNING - R[write to console]: >> InconsistenciasGRUPO16.xlsx -> 3

WARNING - R[write to console]: >> InconsistenciasGRUPO38.xlsx -> 14

WARNING - R[write to console]: >> InconsistenciasGRUPO28.xlsx -> 5

WARNING - R[write to console]: >> InconsistenciasGRUPO34.xlsx -> 2

WARNING - R[write to console]: >> InconsistenciasGRUPO17.xlsx -> 7

WARNING - R[write to console]: >> InconsistenciasGRUPO12.xlsx -> 2

WARNING - R[write to console]: >> InconsistenciasGRUPO21.xlsx -> 2

WARNING - R[write to console]: >> InconsistenciasGRUPO6.xlsx -> 4

WARNING - R[write to console]: >> InconsistenciasGRUPO3.xlsx -> 4

WARNING - R[write to console]: >> InconsistenciasGRUPO24.xlsx -> 5

WARNING - R[write to console]: >> InconsistenciasGRUPO20.xlsx -> 1

WARNING - R[write to console]: >> InconsistenciasGRUPO32.xlsx -> 1

WARNING - R[write to console]: >> InconsistenciasGRUPO27.xlsx -> 1

DEBUG - Generated new state E6yysGu2leNIplNXuwC4Jw7Ugq4csZ.
INFO - "GET /?state=E6yysGu2leNIplNXuwC4Jw7Ugq4csZ&code=4/0Adeu5BWRZrcAwNB4Towddhf_zf8ZO7nFih0DJ2XV1nKLaMAD81lX3p79HBAMgmohVf5h6Q&scope=https://www.googleapis.com/auth/drive HTTP/1.1" 200 65
DEBUG - Encoding `client_id` "915678628628-e8vekd1kcmhi008jphhrs6dsaflmfia2.apps.googleusercontent.com" with `client_secret` as Basic auth credentials.
DEBUG - Requesting url https://oauth2.googleapis.com/token using method POST.
DEBUG - Supplying headers {'Accept': 'application/json', 'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8'} and data {'grant_type': 'authorization_code', 'code': '4/0Adeu5BWRZrcAwNB4Towddhf_zf8ZO7nFih0DJ2XV1nKLaMAD81lX3p79HBAMgmohVf5h6Q', 'redirect_uri': 'http://localhost:55031/'}
DEBUG - Passing through key word arguments {'timeout': None, 'auth': <requests.auth.HTTPBasicAuth object at 0x0000024180627350>, 'verify': True, 'proxies': None, 'cert': None}.
DEBUG - Starting new HTTPS connection (1): oauth2.googleapis.com:443
DEBUG - https://oauth2.googleapis.com:443 "POST /token HTTP/1.1" 200 None
DEBUG - Request to fetch token completed with status 200.
DEBUG - Request url was https://oauth2.googleapis.com/token
DEBUG - Request headers were {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': 'application/json', 'Connection': 'keep-alive', 'Content-Type': 'application/x-www-form-urlencoded;charset=UTF-8', 'Content-Length': '157', 'Authorization': 'Basic OTE1Njc4NjI4NjI4LWU4dmVrZDFrY21oaTAwOGpwaGhyczZkc2FmbG1maWEyLmFwcHMuZ29vZ2xldXNlcmNvbnRlbnQuY29tOkdPQ1NQWC1IbGZ1czJ0LWZtbzBYNWx0UlNiMUVzXzRCSk1p'}
DEBUG - Request body was grant_type=authorization_code&code=4%2F0Adeu5BWRZrcAwNB4Towddhf_zf8ZO7nFih0DJ2XV1nKLaMAD81lX3p79HBAMgmohVf5h6Q&redirect_uri=http%3A%2F%2Flocalhost%3A55031%2F
DEBUG - Response headers were {'Expires': 'Mon, 01 Jan 1990 00:00:00 GMT', 'Date': 'Fri, 25 Aug 2023 18:02:18 GMT', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache, no-store, max-age=0, must-revalidate', 'Content-Type': 'application/json; charset=utf-8', 'Vary': 'Origin, X-Origin, Referer', 'Content-Encoding': 'gzip', 'Server': 'scaffolding on HTTPServer2', 'X-XSS-Protection': '0', 'X-Frame-Options': 'SAMEORIGIN', 'X-Content-Type-Options': 'nosniff', 'Alt-Svc': 'h3=":443"; ma=2592000,h3-29=":443"; ma=2592000', 'Transfer-Encoding': 'chunked'} and content {
  "access_token": "ya29.a0AfB_byBE79qn-CMmraNw8Y86dehvDCXNumW-qxYsAcNucJQYbti-VXjwVJwbaCdMZRuVi12R-I7Q8o7Xm3_BfdVGA2Qu3qdMc5-3N6uuu3_1WJkNs9X5DMyP_useHnJoR8q_3f2v9bUX8bnKHSliF_-mnIq_Ox3F8DpsmQaCgYKAUISARISFQHsvYlsMjRN4WMHb4c_oRyoW0OtMA0173",
  "expires_in": 3599,
  "refresh_token": "1//05uTFnOFS8ltfCgYIARAAGAUSNgF-L9IrpNfGE05QuvdJhhXnwQFFjwK-fGyIu_AJlr6MjVk47RU-VSYitMv55X5YnGDG9nC8EA",
  "scope": "https://www.googleapis.com/auth/drive",
  "token_type": "Bearer"
}.
DEBUG - Invoking 0 token response hooks.
DEBUG - Obtained token {'access_token': 'ya29.a0AfB_byBE79qn-CMmraNw8Y86dehvDCXNumW-qxYsAcNucJQYbti-VXjwVJwbaCdMZRuVi12R-I7Q8o7Xm3_BfdVGA2Qu3qdMc5-3N6uuu3_1WJkNs9X5DMyP_useHnJoR8q_3f2v9bUX8bnKHSliF_-mnIq_Ox3F8DpsmQaCgYKAUISARISFQHsvYlsMjRN4WMHb4c_oRyoW0OtMA0173', 'expires_in': 3599, 'refresh_token': '1//05uTFnOFS8ltfCgYIARAAGAUSNgF-L9IrpNfGE05QuvdJhhXnwQFFjwK-fGyIu_AJlr6MjVk47RU-VSYitMv55X5YnGDG9nC8EA', 'scope': ['https://www.googleapis.com/auth/drive'], 'token_type': 'Bearer', 'expires_at': 1692990281.8821955}.
INFO - file_cache is only supported with oauth2client<4.0.0
